id: 8e88fcf3bb034a16bf03623cb0a27367
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_193-The_Prophecy_of_Sri_Mahadevi-v1
  language: bo
  author: ''
  volume: {}
